### ISSUE TITLE
useSelect `cannot update during an existing state transition` warning using onSelectItemChange with react-router push

### ISSUE THREAD

**Issue by TLadd** [downshift-js/downshift#874]
- `downshift` version: 4.0.1
- `node` version: 10.16.3
- `npm` (or `yarn`) version: yarn 1.21.1

**Relevant code or config**

```javascript
import React from "react";
import * as ReactDOM from "react-dom";
import {
  BrowserRouter as Router,
  Switch,
  Route,
  useHistory
} from "react-router-dom";
import { useSelect } from "downshift";

function App() {
  return (
    <Router>
      <div>
        <NavSelect />
        <Switch>
          <Route path="/about">
            <About />
          </Route>
          <Route path="/users">
            <Users />
          </Route>
          <Route path="/">
            <Home />
          </Route>
        </Switch>
      </div>
    </Router>
  );
}

function NavSelect() {
  const { push } = useHistory();
  const items = ["/about", "/users", "/"];
  const {
    getToggleButtonProps,
    isOpen,
    getMenuProps,
    getItemProps
  } = useSelect({
    onSelectedItemChange: changes => {
      push(changes.selectedItem);
    },
    items
  });
  return (
    <>
      <button type="button" {...getToggleButtonProps()}>
        Toggle
      </button>
      <ul {...getMenuProps()}>
        {isOpen &&
          items.map((item, index) => {
            return (
              <li key={item} {...getItemProps({ index })}>
                {item}
              </li>
            );
          })}
      </ul>
    </>
  );
}

function Home() {
  return <h2>Home</h2>;
}

function About() {
  return <h2>About</h2>;
}

function Users() {
  return <h2>Users</h2>;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**What you did**:

I'm using `useSelect` with an `onSelectItemChange` callback that calls `react-router`'s `push` function to change the route.

**What happened**:

The `push` works, but I end up with this warning in the console:

<img width="945" alt="Screen Shot 2020-01-03 at 4 01 13 PM" src="https://user-images.githubusercontent.com/5084492/71751808-64ad0000-2e42-11ea-9444-c91657cc67cc.png">

```
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state. 
    in NavSelect (at src/​index.js:15)
    in App (at src/​index.js:78)
```

**Reproduction repository**:

https://codesandbox.io/s/hopeful-currying-hvx2p

**Problem description**:

There seems to be some specific incompatibility between where `onSelectITemChange` is called and how `push` works. I don't quite understand it yet. `push` [calls history's setState](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L190) (not React's), which [calls notifyListeners](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L85) which [calls react-router's history listener](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L33).

**Suggested solution**:

Unsure.

```
    onSelectedItemChange: changes => {
      setTimeout(() => {
        push(changes.selectedItem);
      });
    },
```

works as a workaround.

**Comment by TLadd** [comment]
Created another [CodeSandbox](https://codesandbox.io/s/charming-goldwasser-s20rz) that results in this warning and has the same basic scenario that is taking place between react-router-dom and downshift.

```
import React from "react";
import ReactDOM from "react-dom";

import "./styles.css";

// stand-in for history.listen
let listener = () => {};
// stand-in for history location
let count = 0;
// stand-in for `push`
const incCount = () => {
  count++;
  listener();
};

function App() {
  // stand-in for useEnhancedReducer
  const [state, dispatch] = React.useReducer(
    (state, action) => {
      switch (action.type) {
        default:
          incCount();
          return { flag: !state.flag };
      }
    },
    { flag: true }
  );

  return (
    <div className="App">
      <ComponentWithListenerSetInConstructor>
        {({ countInState }) => {
          return (
            <div>
              <h1>Hello CodeSandbox</h1>
              <h2>Start editing to see some magic happen!</h2>
              <button
                onClick={() => {
                  dispatch({ type: "GREAT" });
                }}
                type="button"
              >
                Click
              </button>
              {countInState}
              {String(state.flag)}
            </div>
          );
        }}
      </ComponentWithListenerSetInConstructor>
    </div>
  );
}

class ComponentWithListenerSetInConstructor extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      count: count
    };

    listener = () => {
      this.setState({
        count: count
      });
    };
  }

  render() {
    return <>{this.props.children({ countInState: this.state.count })}</>;
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

In this example, the React.useReducer is acting similarly to `useEnhancedReducer`; it calls `incCount`, which is equivalent to `useEnhancedReducer` calling `push` through `onSelectedItemChange`. `ComponentWithListenerSetInConstructor` is acting like the `Router` component of react-router-dom, setting up the listener and syncing up state whenever the listener is called.

**Comment by silviuavram** [comment]
Should we follow up with issues on react / react-router-dom? I don't know what's the issue so we may need some help.

**Comment by TLadd** [comment]
Added an issue in react-router. Will see what they say and proceed accordingly, perhaps filing an issue in React.

**Comment by TLadd** [comment]
Issue in react-router was closed. From timdorr's explanation, it seems like `window.history` can be changed during a render cycle, but that's just creating an opportunity for something else to be calling it at the wrong time.

So the `onSelectedItemChange`, which is calling `push` in this case, gets called as a result of [`callOnChangeProps` in `useEnhancedReducer`](https://github.com/downshift-js/downshift/blob/master/src/hooks/utils.js#L94). 

When first looking at `useEnhancedReducer`, I found it to be a bit non-standard, since it's calling callbacks inside a reducer. Just a hunch, but it sticks out to me as something that could be unsafe. I would typically expect `useReducer` to just handle the state updates and then a separate `useEffect` to detect changes in state and call the appropriate callbacks. I'm guessing there was a reason to go with the `useEnhancedReducer` approach as opposed to a separate `useEffect`?

**Comment by silviuavram** [comment]
useEnhancedReducer is like that as we had to properly handle the controlled prop scenarios inside the useReducer logic. PR is https://github.com/downshift-js/downshift/pull/774 There is an issue attached as well.

I don't know React that well to fix this at the moment, but if you have an idea then we can start looking into it. Thanks!

**Comment by federico-qadra** [comment]
I have the same problem but using `useCombobox` and `Formik`.

I have a Combobox component in my app that does this.

```
const combobox = useCombobox({
  onSelectedItemChange: changes => {
    if (changes.itemSelected) onChange(itemSelected)
  }
)
```


Then in the render prop of `Formik`

```
<Combobox
  onChange={item => {
    if (item) setFieldValue('city', item.city)
  }}
/> 

```

Using the same component outside of `Formik` works fine.

**Comment by cannatrade** [comment]
Same problem when using `useCombobox` and `react-instantsearch-dom`

**Comment by silviuavram** [comment]
We should take a look at the useEnhancedReducer and see how it can be
fixed, maybe move the call of callbacks somewhere else. If someone wants to
take a look at it great, I’m on a small vacay atm. 🙂

**Comment by mufasa71** [comment]
@silviuavram I prepared pull request and tested it with `react-router-dom` and `react-instantsearch-dom`, works good as for me.

**Comment by silviuavram** [comment]
Awesome. I will release an alpha to check the sandbox with the issue. A sandbox with react-instantsearch-dom would be useful as well.

**Comment by mufasa71** [comment]
https://codesandbox.io/s/busy-wilson-exk8t

I prepared sandbox, thanks

**Comment by denchen** [comment]
Just for clarification, this is still an issue since #912 was reverted, correct? I'm seeing these warnings on `v5.0.0`, which I assume has #930. Should this be re-opened?

**Comment by silviuavram** [comment]
I thought this was re-opened, thanks for pointing that out.

I tried a small change from the original PR https://github.com/downshift-js/downshift/pull/952.

@TLadd @mufasa71 can you take a look? In the controlled docs example for me it seems to work. Maybe you can help me test this out. Thanks!

**Comment by mufasa71** [comment]
@silviuavram i will look into it one more time, will try to fix it in other way

**Comment by DominicTobias-b1** [comment]
This is still broken in 5.0.5, I'm using `useSelect`. I'm not sure what you're doing internally but this will typically happen if you respond to an event not triggered in a typical way in a hook and then do something which causes the hook to re-render out of sync with React's render cycle. If instead you use `useEffect` or another hook as an intermediate step in reacting to the change then it properly syncs with React.

**Comment by silviuaavram** [comment]
Will continue to track this issue at https://github.com/downshift-js/downshift/issues/962 and will attempt to fix it.
